//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAsync.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Area()
        {
            this.TB_Hospital = new HashSet<TB_Hospital>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Province_ID { get; set; }
        public string Province_Name { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string City_Name { get; set; }
        public Nullable<int> District_ID { get; set; }
        public string District_Name { get; set; }
        public string Level { get; set; }
        public string Tel_Code { get; set; }
        public string Zip_Code { get; set; }
        public string Pin_Yin { get; set; }
        public string English { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<System.DateTime> Add_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Hospital> TB_Hospital { get; set; }
    }
}
