//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAsync.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Dyestuff_Validation
    {
        public long ID { get; set; }
        public string Dye_Number { get; set; }
        public Nullable<int> Equipment_ID { get; set; }
        public string Gr_Channel { get; set; }
        public Nullable<decimal> Slot_1 { get; set; }
        public Nullable<decimal> Slot_2 { get; set; }
        public Nullable<decimal> Slot_3 { get; set; }
        public Nullable<decimal> Slot_4 { get; set; }
        public Nullable<decimal> Slot_5 { get; set; }
        public Nullable<decimal> Slot_6 { get; set; }
        public Nullable<decimal> Slot_7 { get; set; }
        public Nullable<decimal> Slot_8 { get; set; }
        public Nullable<decimal> Slot_9 { get; set; }
        public Nullable<decimal> Slot_10 { get; set; }
        public Nullable<decimal> Slot_11 { get; set; }
        public Nullable<decimal> Slot_12 { get; set; }
        public bool Is_Effective { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Add_Time { get; set; }
    
        public virtual TB_Equipment TB_Equipment { get; set; }
    }
}
