//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAsync.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Fluorescence
    {
        public long ID { get; set; }
        public Nullable<int> Experiment_ID { get; set; }
        public Nullable<int> Slot { get; set; }
        public Nullable<decimal> G_Inital_Fluorescence { get; set; }
        public Nullable<decimal> R_Inital_Fluorescence { get; set; }
        public Nullable<decimal> G_Standard_Fluorescence { get; set; }
        public Nullable<decimal> R_Standard_Fluorescence { get; set; }
        public Nullable<int> Cycle_No { get; set; }
        public Nullable<System.DateTime> Add_Time { get; set; }
    
        public virtual TB_Experiment TB_Experiment { get; set; }
    }
}
