//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAsync.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Login_Log
    {
        public int ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Login_PWD { get; set; }
        public Nullable<int> Equipment_ID { get; set; }
        public Nullable<System.DateTime> Add_Time { get; set; }
        public bool Is_Effective { get; set; }
    
        public virtual TB_Equipment TB_Equipment { get; set; }
        public virtual TB_USER TB_USER { get; set; }
    }
}
