//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAsync.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OpEnvironment_Temperature
    {
        public long ID { get; set; }
        public Nullable<int> OpEnvironment_Id { get; set; }
        public string File_Path { get; set; }
        public Nullable<System.DateTime> Add_Time { get; set; }
    
        public virtual TB_OpEnvironment TB_OpEnvironment { get; set; }
    }
}
