//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAsync.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SSIS_Errors
    {
        public int ID { get; set; }
        public System.DateTime ErrorDateTime { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public string SourceName { get; set; }
    }
}
