//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAsync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Equipment()
        {
            this.TB_Dyestuff_Validation = new HashSet<TB_Dyestuff_Validation>();
            this.TB_Login_Log = new HashSet<TB_Login_Log>();
            this.TB_OpEnvironment = new HashSet<TB_OpEnvironment>();
            this.TB_Experiment = new HashSet<TB_Experiment>();
        }
    
        public int ID { get; set; }
        public string Machine_ID { get; set; }
        public string Machine_Code { get; set; }
        public Nullable<int> Hospital_ID { get; set; }
        public Nullable<System.DateTime> Add_Time { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public bool Is_Effective { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Dyestuff_Validation> TB_Dyestuff_Validation { get; set; }
        public virtual TB_Hospital TB_Hospital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Login_Log> TB_Login_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_OpEnvironment> TB_OpEnvironment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Experiment> TB_Experiment { get; set; }
    }
}
