//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAsync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Patient
    {
        public long ID { get; set; }
        public Nullable<int> Hospital_ID { get; set; }
        public Nullable<int> Experiment_ID { get; set; }
        public Nullable<long> Experiment_Rrsult_ID { get; set; }
        public string Patient_Name { get; set; }
        public string Hospital_No { get; set; }
        public string Gender { get; set; }
        public string Operator_Name { get; set; }
        public string Patient_Birth_Day { get; set; }
        public string Patient_ID_No { get; set; }
        public string Patient_Tel { get; set; }
        public string Hospital_Department { get; set; }
        public Nullable<int> Patient_Age { get; set; }
        public Nullable<System.DateTime> Run_Time { get; set; }
        public Nullable<int> Slot { get; set; }
        public Nullable<int> Gene_Locus_ID { get; set; }
        public string Inspection_Unit { get; set; }
        public string For_Drug { get; set; }
        public string Patient_Bar_Code { get; set; }
        public Nullable<System.DateTime> Add_Time { get; set; }
        public Nullable<System.DateTime> Reported_Time { get; set; }
        public string Remark { get; set; }
    
        public virtual TB_Hospital TB_Hospital { get; set; }
        public virtual TB_Experiment TB_Experiment { get; set; }
    }
}
