//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAsync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_System_Param
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_System_Param()
        {
            this.TB_OpEnvironment = new HashSet<TB_OpEnvironment>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> Curve_Growth_Multiple { get; set; }
        public Nullable<decimal> Growth_Cycles_Numbers { get; set; }
        public Nullable<decimal> CT_Range_Max { get; set; }
        public Nullable<decimal> CT_Range_Min { get; set; }
        public Nullable<decimal> Minimum_Normalized_Fluorescence { get; set; }
        public Nullable<decimal> GR_Ration_Max { get; set; }
        public Nullable<decimal> GR_Ration_Min { get; set; }
        public Nullable<decimal> Rd { get; set; }
        public Nullable<decimal> Net_Of_Linear_Growth { get; set; }
        public Nullable<bool> Is_Slot_Corrected { get; set; }
        public Nullable<System.DateTime> Add_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_OpEnvironment> TB_OpEnvironment { get; set; }
    }
}
