//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAsync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Sample_Gene
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Sample_Gene()
        {
            this.TB_Experiment_Info = new HashSet<TB_Experiment_Info>();
        }
    
        public int ID { get; set; }
        public string Staff_Name { get; set; }
        public bool Is_Effective { get; set; }
        public Nullable<int> Gene_Locus_ID { get; set; }
        public Nullable<int> Gene_Result_ID { get; set; }
        public Nullable<System.DateTime> Add_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Experiment_Info> TB_Experiment_Info { get; set; }
        public virtual TB_Gene_Locus TB_Gene_Locus { get; set; }
        public virtual TB_Gene_Result TB_Gene_Result { get; set; }
    }
}
